### ISSUE TITLE
TWA-VF: Layer tree CSS needs adjusting

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#978]
Specifically on 4K displays on visualisations with lots of layers, the layer tree extends beyond the end of the containing control block; fixing this requires some CSS tweaks and testing on different display sizes.

**Comment by Ushcode** [comment]
```css

#layerContainer {
	display: flex;
	flex-flow: column;
	overflow: hidden;
}

#layerContainer .controlContents {
	display: flex;
	flex-grow: 1;
	overflow: hidden;
}

#layerTreeContainer {
	overflow: scroll;
}
```
